"""
check_isi_step.py -- integration-step check for the CIR-based model (Section IV).

Repeats the static-channel run and the T_c = 240 time-varying run of run_waveform_isi.py for the two narrowest pulses
(T_sym / t_peak = 12 and 16) with the integration step of the sweep (0.01) and with the step halved and quartered
(0.005 and 0.0025), with everything else unchanged (seeds, setpoints, K_base, and 40 trajectories).  Reports the
largest relative change of the closed-loop error probabilities, the largest change of the tracking error, and the
deviation of the on-grid peak sample from the true peak value.

Outputs: results/waveform_isi_step.json and the LaTeX macros manuscript/numbers/numbers_isi_check.tex.
Option: --macros-only (rewrite the macros from the stored results without simulating).
"""
from __future__ import annotations

import json, math, os, sys, time
import numpy as np
from scipy.stats import binom

sys.path.insert(0, os.path.dirname(__file__))
import run_waveform_isi as R
import model as M

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "results")
NUMBERS = os.path.join(HERE, "..", "manuscript", "numbers")
RATIOS, DTS = (12, 16), (0.01, 0.005, 0.0025)
SWEEP = json.load(open(os.path.join(OUT, "waveform_isi.json")))["ratios"]


def run_case(ratio, dt, n_traj=40, t_burn=300.0, t_win=300.0):
    D = ratio / (6.0 * R.T_SYM); r = SWEEP[str(ratio)]; K_best, s_star = r["K_best_fixed"], r["s_star"]
    t_end = t_burn + t_win
    B = R.build(n_traj, t_end, dt, seed=M.stable_seed("wf-levels", base=9), D=D)
    rec = np.array([j for j in range(B["peak_vals"].shape[1]) if j * R.T_SYM >= t_burn - 1e-9])
    y, clip = R.run_loop(B["wave"], n_traj, t_end, dt, t_burn, seed=M.stable_seed("wf", "waveform_renorm", base=9), setpoint=s_star)
    e = dict(ratio=ratio, dt=dt, bep_fixed=R.bep_peaks(B["peak_vals"], B["bits"], rec, K=K_best),
             bep_loop=R.bep_peaks(B["peak_vals"], B["bits"], rec, y=y), clip_static=clip)
    T_sw = 240.0; lnS = np.log(R.S_SW)
    g_t = lambda tt: float(np.exp(-0.5 * lnS * (1.0 - np.cos(2 * np.pi * tt / T_sw))))
    t_end_sw = 200.0 + 2 * T_sw
    Bsw = R.build(n_traj, t_end_sw, dt, seed=M.stable_seed("wf-levels-sw", base=9), D=D)
    gvec = np.array([g_t(i * dt) for i in range(Bsw["n_steps"])]); Wsw = Bsw["wave"] * gvec[None, :]
    rec_sw = np.array([j for j in range(Bsw["peak_vals"].shape[1]) if j * R.T_SYM >= 200.0 - 1e-9])
    g_peaks = np.array([g_t(j * R.T_SYM) for j in range(Bsw["peak_vals"].shape[1])]); pv_sw = Bsw["peak_vals"] * g_peaks[None, :]
    K_or = K_best * g_peaks[rec_sw]; c = pv_sw[:, rec_sw].T; bb = Bsw["bits"][:, rec_sw].T
    th = np.clip(c / (c + K_or[:, None]), 1e-12, 1 - 1e-12); m = R.NR // 2
    ee = np.where(bb == 0, binom.sf(m, R.NR, th) + 0.5 * binom.pmf(m, R.NR, th), binom.cdf(m - 1, R.NR, th) + 0.5 * binom.pmf(m, R.NR, th))
    bst = R.best_static(pv_sw, Bsw["bits"], rec_sw, min(n_traj, 8))
    y_sw, clip_sw = R.run_loop(Wsw, n_traj, t_end_sw, dt, 200.0, seed=M.stable_seed("wf-sw", base=9), setpoint=s_star)
    b_ad = R.bep_peaks(pv_sw, Bsw["bits"], rec_sw, y=y_sw)
    kd_sw = M.kd_of_y(y_sw, R.ALPHA); tgt = K_best * g_peaks[rec_sw][:kd_sw.shape[0]]
    e.update(oracle=float(ee.mean()), static_best=bst[0], adaptive=b_ad, gain=bst[0] / b_ad,
             track_err_ln=float(np.mean(np.abs(np.log(kd_sw.mean(axis=1) / tgt)))), clip_sw=clip_sw)
    return e


def max_trk_dev_pts(res):
    """Largest change of the tracking error 100 (e^x - 1) %, with x the mean |ln(<K_D>/K_opt)|, over the step sizes."""
    ref_dt = res["dts"][0]
    return max(abs(100 * (math.exp(res["cases"][f"{r}|{dt}"]["track_err_ln"]) - math.exp(res["cases"][f"{r}|{ref_dt}"]["track_err_ln"])))
               for r in res["ratios"] for dt in res["dts"][1:])


def write_macros(res, path=os.path.join(NUMBERS, "numbers_isi_check.tex")):
    """LaTeX macros of the integration-step check (Section IV) from the stored results."""
    res = dict(res, max_trk_dev_pts=max_trk_dev_pts(res))
    lines = ["% numbers_isi_check.tex -- generated by code/check_isi_step.py; do not edit.",
             f"\\newcommand{{\\wfStepMaxBepDevPct}}{{{math.ceil(100 * res['max_bep_dev'])}}}",
             f"\\newcommand{{\\wfStepMaxTrkDevPts}}{{{res['max_trk_dev_pts']:.1f}}}",
             f"\\newcommand{{\\wfStepPeakSamplePct}}{{{res['peak_offset_pct']:.2f}}}",
             f"\\newcommand{{\\wfStepPeakStepsTwelve}}{{{res['peak_sample']['12']['steps']:.1f}}}",
             f"\\newcommand{{\\wfStepPeakStepsSixteen}}{{{res['peak_sample']['16']['steps']:.1f}}}"]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(path))


if __name__ == "__main__":
    if "--macros-only" in sys.argv:
        write_macros(json.load(open(os.path.join(OUT, "waveform_isi_step.json"))))
        sys.exit(0)
    t0 = time.time()
    M.set_actuator("exp", kbase=R.KBASE_WF)
    res = dict(ratios=list(RATIOS), dts=list(DTS), cases={}, peak_sample={})
    try:
        for ratio in RATIOS:
            for dt in DTS:
                e = run_case(ratio, dt); res["cases"][f"{ratio}|{dt}"] = e
                print(f"ratio {ratio:2d} dt={dt}: fixed={e['bep_fixed']:.3e} loop={e['bep_loop']:.3e} adaptive={e['adaptive']:.3e} "
                      f"static={e['static_best']:.3e} gain={e['gain']:.2f} trk={100 * (math.exp(e['track_err_ln']) - 1):.1f}%  [{time.time() - t0:.0f} s]", flush=True)
    finally:
        M.set_actuator("exp", kbase=M.KBASE)
    # on-grid peak sample: the impulse is placed round(t_peak/dt) steps before the peak sample (build), so the sample sees h(round(t_peak/dt) dt)
    for ratio in (3, 4, 6, 8, 12, 16):
        D = ratio / (6.0 * R.T_SYM); tp = 1.0 / (6 * D); i_off = int(round(tp / 0.01))
        res["peak_sample"][str(ratio)] = dict(t_peak=tp, steps=tp / 0.01, h_over_peak=float(R.h(i_off * 0.01, D) / R.h(tp, D)))
    devs, trk = [], []
    for ratio in RATIOS:
        ref = res["cases"][f"{ratio}|0.01"]
        for dt in DTS[1:]:
            e = res["cases"][f"{ratio}|{dt}"]
            devs += [abs(e["bep_loop"] / ref["bep_loop"] - 1), abs(e["adaptive"] / ref["adaptive"] - 1)]
            trk.append(abs(100 * (math.exp(e["track_err_ln"]) - math.exp(ref["track_err_ln"]))))
    res["max_bep_dev"], res["max_trk_dev_pts"] = max(devs), max(trk)
    res["peak_offset_pct"] = 100 * (1 - min(v["h_over_peak"] for v in res["peak_sample"].values()))
    json.dump(res, open(os.path.join(OUT, "waveform_isi_step.json"), "w"), indent=1, default=float)
    write_macros(res)
    print(f"max BEP deviation {100 * res['max_bep_dev']:.1f} %, max tracking deviation {res['max_trk_dev_pts']:.2f} points, "
          f"peak offset {res['peak_offset_pct']:.2f} %  ({time.time() - t0:.0f} s)")
