"""
check_modification_bep.py -- static-channel BEP of the explicit-modification model (Section IV-B).

In the reduced model, the affinity follows the modulator directly, K_D = K_base exp(-alpha y), such that the affinity
fluctuation is set by the modulator variance (results/bep_hc.json).  With the modification level m as an additional
variable (results/modification.json, k_d = 5 gamma_p), the affinity follows m, K_D = K_base exp(-a m), and the
modification stage filters the modulator fluctuations.  This script evaluates the exact error probability of the
fixed-threshold detector for a Gaussian log-affinity fluctuation with the measured mean and variance of each model
(Gauss-Hermite quadrature, n_H = 1) and compares the predicted and the measured reduction of the BEP.  It uses stored
results only.

Outputs: results/modification_check.json and the LaTeX macros manuscript/numbers/numbers_mod_check.tex.
"""
from __future__ import annotations

import json, os, sys
import numpy as np
from scipy.stats import binom

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import model as M

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "results")
NUMBERS = os.path.join(HERE, "..", "manuscript", "numbers")
C0, C1, NR, OMEGA = M.CL0_NOM, M.CL1_NOM, M.N_RECEPTORS, M.OMEGA_HC


def bep_at(kd):
    """Exact error probability of the fixed-threshold detector at a fixed affinity kd (n_H = 1)."""
    th0, th1 = C0 / (C0 + kd), C1 / (C1 + kd)
    m = NR // 2
    e0 = binom.sf(m, NR, th0) + 0.5 * binom.pmf(m, NR, th0)
    e1 = binom.cdf(m - 1, NR, th1) + 0.5 * binom.pmf(m, NR, th1)
    return 0.5 * (e0 + e1)


def bep_gauss_logkd(kd_mean, var_lnkd, n=200):
    """Exact-binomial BEP averaged over ln K_D ~ N(ln kd_mean - var/2, var), i.e., with the mean of K_D at kd_mean."""
    x, w = np.polynomial.hermite_e.hermegauss(n)
    mu = np.log(kd_mean) - 0.5 * var_lnkd
    kd = np.exp(mu + np.sqrt(var_lnkd) * x)
    return float(np.sum(w * np.array([bep_at(k) for k in kd])) / np.sqrt(2 * np.pi))


def compute():
    """Predicted and measured BEP reduction of the explicit-modification model relative to the reduced model."""
    hc = json.load(open(os.path.join(OUT, "bep_hc.json")))["configs"]["allosteric|AIF"]
    mo = json.load(open(os.path.join(OUT, "modification.json")))
    c5 = mo["cases"]["5"]; alpha = mo["alpha"]; a = c5["a"]
    red = dict(kd_mean=hc["mean_kd"], var_omega=hc["var_dy_omega"], var_lnkd=alpha ** 2 * hc["var_dy_omega"] / OMEGA, bep=hc["bep"])
    exp = dict(kd_mean=c5["kd_mean"], var_omega=c5["var_m_omega"], var_lnkd=a ** 2 * c5["var_m_omega"] / OMEGA, bep=c5["bep"],
               var_y_omega=c5["var_y_omega"])
    for d in (red, exp):
        d["bep_pred"] = bep_gauss_logkd(d["kd_mean"], d["var_lnkd"])
    return dict(reduced=red, explicit=exp,
                var_reduction_pct=100 * (1 - exp["var_omega"] / red["var_omega"]),
                bep_pred_reduction_pct=100 * (1 - exp["bep_pred"] / red["bep_pred"]),
                bep_meas_reduction_pct=100 * (1 - exp["bep"] / red["bep"]))


def write_macros(res, path=os.path.join(NUMBERS, "numbers_mod_check.tex")):
    """LaTeX macros of Section IV-B (the variance itself, modFiveVarM, is written by make_numbers.py)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = ["% numbers_mod_check.tex -- generated by code/check_modification_bep.py; do not edit.",
             f"\\newcommand{{\\modFiveVarMRedPct}}{{{res['var_reduction_pct']:.1f}}}",
             f"\\newcommand{{\\modFiveBepPredRedPct}}{{{res['bep_pred_reduction_pct']:.0f}}}",
             f"\\newcommand{{\\modFiveBepMeasRedPct}}{{{res['bep_meas_reduction_pct']:.0f}}}"]
    open(path, "w").write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(path))


if __name__ == "__main__":
    res = compute()
    json.dump(res, open(os.path.join(OUT, "modification_check.json"), "w"), indent=1)
    write_macros(res)
    print(json.dumps(res, indent=1))
