"""
make_numbers.py -- every number of the paper as a LaTeX macro.

Reads the result files in ../results and writes every number that appears in the manuscript as a LaTeX macro, such
that no number is typed by hand:
    manuscript/numbers/numbers.tex            main results (this script)
    manuscript/numbers/numbers_isi.tex        CIR-based model sweep (run_waveform_isi.write_macros)
    manuscript/numbers/numbers_isi_check.tex  integration-step check (check_isi_step.write_macros)
    manuscript/numbers/numbers_mod_check.tex  explicit-modification check (check_modification_bep.write_macros)
Macro names contain letters only, as required by LaTeX.  Missing result files are skipped with a warning.

Usage:  python3 make_numbers.py
"""
from __future__ import annotations

import json, os, sys, math
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results")
NUMBERS = os.path.join(HERE, "..", "manuscript", "numbers")
os.makedirs(NUMBERS, exist_ok=True)

sys.path.insert(0, HERE)
import model as M


# --------------------------------------------------------------------------- #
#  formatting
# --------------------------------------------------------------------------- #
def sci(x, digits=1):
    """4.36e-06 -> 4.4\\times10^{-6}  (math mode content, no $)."""
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "--"
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    m = x / 10 ** e
    if round(m, digits) >= 10:
        m /= 10; e += 1
    if e == 0:
        return f"{m:.{digits}f}"
    return rf"{m:.{digits}f}\times10^{{{e}}}"


def fix(x, d=2):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "--"
    return f"{x:.{d}f}"


def sig(x, d=2):
    """d significant figures, plain."""
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "--"
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    v = round(x, d - 1 - e)
    return f"{v:g}" if abs(v) < 1e6 else sci(v, d - 1)


DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five",
          "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def name_ok(s):
    """LaTeX macro names must be letters only: spell digits out, drop the rest."""
    return "".join(DIGITS[ch] if ch.isdigit() else ch for ch in s if ch.isalnum())


class Macros:
    def __init__(self):
        self.items = []
        self.names = set()

    def add(self, name, value, comment=""):
        name = name_ok(name)
        if name in self.names:
            raise ValueError(f"duplicate macro {name}")
        self.names.add(name)
        self.items.append((name, str(value), comment))

    def write(self, path):
        with open(path, "w") as f:
            f.write("% numbers.tex -- generated by code/make_numbers.py; do not edit.\n")
            for n, v, c in self.items:
                if c.startswith("% "):
                    c = "[%] " + c[2:]
                f.write(f"\\newcommand{{\\{n}}}{{{v}}}" + (f"  % {c}" if c else "") + "\n")
        print(f"wrote {os.path.normpath(path)}  ({len(self.items)} macros)")


def load(name):
    p = os.path.join(RES, name)
    if not os.path.exists(p):
        print(f"  [skip] {name} not found")
        return None
    return json.load(open(p))


def loginterp_x(xs, ys, y_target):
    """x at which the (log-log) interpolated curve first reaches y_target; None if never."""
    xs, ys = np.asarray(xs, float), np.asarray(ys, float)
    for j in range(1, len(xs)):
        if ys[j] >= y_target > ys[j - 1] or (ys[j - 1] >= y_target > ys[j]):
            lx = np.interp(np.log(y_target), sorted([np.log(ys[j - 1]), np.log(ys[j])]),
                           [np.log(xs[j - 1]), np.log(xs[j])] if ys[j - 1] < ys[j] else [np.log(xs[j]), np.log(xs[j - 1])])
            return float(np.exp(lx))
    if ys[0] >= y_target:
        return float(xs[0])
    return None


TAG = {"allosteric": "Allo", "cooperative": "Coop", "coregulated": "Coreg", "weighted": "Wtd",
       "cooperative_a1": "CoopAone", "coregulated_slow": "CoregSlow"}

if __name__ == "__main__":
    mac = Macros()

    # ---- Table I: parameters -------------------------------------------------
    mac.add("pMu", M.MU); mac.add("pTheta", M.THETA); mac.add("pK", M.K); mac.add("pEta", M.ETA)
    mac.add("pGp", M.GP); mac.add("pEps", M.EPS); mac.add("pEtaOne", M.ETA1)
    mac.add("pKbase", fix(M.KBASE, 2)); mac.add("pKdopt", fix(M.KD_OPT, 1))
    mac.add("pClZero", fix(M.CL0_NOM, 1)); mac.add("pClOne", fix(M.CL1_NOM, 1))
    mac.add("pNcoop", fix(M.N_COOP, 1)); mac.add("pNbase", fix(M.N_BASE, 1)); mac.add("pKappa", fix(M.KAPPA, 1))
    mac.add("pW", fix(M.W_WEIGHT, 1)); mac.add("pOmegaHC", int(M.OMEGA_HC)); mac.add("pNR", M.N_RECEPTORS)
    mac.add("pTc", int(M.T_C)); mac.add("pWcMin", fix(M.WC_MIN, 4)); mac.add("pTsym", fix(M.T_SYM, 1))
    mac.add("pTimeUnit", fix(M.TIME_UNIT_S, 0)); mac.add("pKfix", fix(M.K_FIX, 1))
    mac.add("pNtun", int(round(M.W_WEIGHT * M.N_RECEPTORS))); mac.add("pNfix", int(round((1 - M.W_WEIGHT) * M.N_RECEPTORS)))

    # ---- design points and Table II -----------------------------------------
    dp = load("design_points.json")
    if dp:
        for s, r in dp["design"].items():
            t = TAG[s]
            mac.add(f"dp{t}Alpha", fix(r["alpha"], 3)); mac.add(f"dp{t}Ystar", fix(r["ys"], 2))
            mac.add(f"dp{t}Zeta", fix(r["zeta"], 3)); mac.add(f"dp{t}Rho", fix(r["rho"], 3))
            mac.add(f"dp{t}Wc", fix(r["wc"], 4)); mac.add(f"dp{t}Settling", fix(r["tau"], 1))
            mac.add(f"dp{t}Tau", fix(r["tau"], 1)); mac.add(f"dp{t}TauFull", fix(r["tau_full"], 1))
            mac.add(f"dp{t}VarDy", fix(r["var_dy_chem"], 2), "full linear-noise approximation, reaction noise only (Omega-scaled)")
            mac.add(f"dp{t}VarDyRed", fix(r["var_dy_reduced_chem"], 2), "reduced-loop closed form")
            mac.add(f"dp{t}VarDyBits", fix(r["var_dy"], 1), "full linear-noise approximation incl. self-noise, Omega = 200")
            mac.add(f"dp{t}VarDyBitsTerm", fix(r["var_dy_bits_term"], 1))
            mac.add(f"dp{t}Dbits", fix(r["d_bits"], 4))
            mac.add(f"dp{t}ZetaCrit", fix(r["zeta_crit"], 2)); mac.add(f"dp{t}Margin", fix(r["margin"], 0))
            mac.add(f"dp{t}Dmu", fix(r["dmu"], 3)); mac.add(f"dp{t}SigZero", fix(r["sig0"], 4)); mac.add(f"dp{t}SigOne", fix(r["sig1"], 4))
            mac.add(f"dp{t}BepSurr", sci(r["bep"])); mac.add(f"dp{t}Nh", fix(r["n_h"], 2))
            mac.add(f"dp{t}MuZero", fix(r["th0"], 3)); mac.add(f"dp{t}MuOne", fix(r["th1"], 3))
            mac.add(f"dp{t}Inventory", fix(r["inventory"], 0)); mac.add(f"dp{t}Zone", fix(r["z1"], 2)); mac.add(f"dp{t}Ztwo", fix(r["z2"], 3))
            mac.add(f"dp{t}EtaZsum", fix(M.ETA * (r["z1"] + r["z2"]), 2)); mac.add(f"dp{t}K", fix(r.get("k", M.K), 3))
            bb = r.get("k", M.K) * r["rho"] * M.THETA * r["zeta"]
            mac.add(f"dp{t}LoopGain", fix(bb, 4), "b = k rho theta zeta*")
            tau_lf = M.GP / bb
            mac.add(f"dp{t}TauLF", fix(tau_lf, 1), "low-frequency tracking time gamma_p/b")
            mac.add(f"dp{t}SnrBits", fix(np.sqrt(8 * tau_lf / M.T_SYM), 1), "Delta-theta/sigma_SN = sqrt(8 tau_LF/T_sym), self-noise only (reduced white-noise model)")
            mac.add(f"dp{t}SnrBitsDom", fix(np.sqrt(8 * r["tau"] / M.T_SYM), 1), "same with the dominant-pole tau (slow-loop approximation)")
        for s, r in dp["min_margin"].items():
            mac.add(f"minMargin{TAG[s]}", fix(r["margin"], 1))
        mac.add("minMarginAll", fix(min(r["margin"] for r in dp["min_margin"].values()), 1))
        rc = dp.get("coregulated_unconstrained")
        if rc:
            mac.add("dpCoregUnconAlpha", fix(rc["alpha"], 2)); mac.add("dpCoregUnconNh", fix(rc["n_h"], 2))
            mac.add("dpCoregUnconBepSurr", sci(rc["bep"]))
        th0 = 1 / (1 + 4 ** 0.5); mac.add("thetaZeroAllo", fix(th0, 3))
        th0c = 1 / (1 + 4 ** (M.N_COOP / 2)); mac.add("thetaZeroCoop", fix(th0c, 3))
        mac.add("gainFactorAllo", fix(th0 * (1 - th0), 3), "theta0 theta1 = 2/9 for n=1")
        mac.add("gainFactorCoop", fix(th0c * (1 - th0c), 3))
        mac.add("gainNaiveExcessAllo", fix(100 * (0.25 / (th0 * (1 - th0)) - 1), 0), "% by which n alpha/4 exceeds true gain")
        mac.add("gainNaiveExcessCoop", fix(100 * (0.25 / (th0c * (1 - th0c)) - 1), 0))
        # ratio of the self-noise to the reaction-noise intensity at Omega = 200
        d = dp["design"]
        mac.add("bitsOverChemAllo", fix(M.OMEGA_HC * d["allosteric"]["d_bits"] / (2 * M.MU), 1), "Omega D_bits / 2mu")
        mac.add("bitsOverChemCoop", fix(M.OMEGA_HC * d["cooperative"]["d_bits"] / (2 * M.MU), 1))
        mac.add("memorySymbolsAllo", fix(d["allosteric"]["tau"] / M.T_SYM, 0), "tau / T_sym")
        mac.add("memorySymbolsCoreg", fix(d["coregulated"]["tau"] / M.T_SYM, 0))
        mac.add("ctrlNoiseRatioCoopAllo", fix((d["cooperative"]["zeta"] ** 2 * d["cooperative"]["var_dy_chem"]) /
                                              (d["allosteric"]["zeta"] ** 2 * d["allosteric"]["var_dy_chem"]), 2),
                "reaction noise at the detector input, cooperative / non-cooperative")
        mac.add("ctrlNoiseExcessCoopPct", fix(100 * ((d["cooperative"]["zeta"] ** 2 * d["cooperative"]["var_dy_chem"]) /
                                                     (d["allosteric"]["zeta"] ** 2 * d["allosteric"]["var_dy_chem"]) - 1), 0))
        mac.add("bitsNoiseRatioCoopAllo", fix((d["cooperative"]["zeta"] ** 2 * d["cooperative"]["var_dy_bits_term"]) /
                                              (d["allosteric"]["zeta"] ** 2 * d["allosteric"]["var_dy_bits_term"]), 1),
                "self-noise at the detector input, cooperative / non-cooperative")
        mac.add("totalNoiseRatioCoopAllo", fix((d["cooperative"]["zeta"] ** 2 * d["cooperative"]["var_dy"]) /
                                               (d["allosteric"]["zeta"] ** 2 * d["allosteric"]["var_dy"]), 1),
                "total noise at the detector input incl. self-noise, cooperative / non-cooperative")
        for s_ in ("allosteric", "cooperative"):
            bb = d[s_].get("k", M.K) * d[s_]["rho"] * M.THETA * d[s_]["zeta"]
            mac.add(f"bitsSnrSq{TAG[s_]}", fix(bb * M.T_SYM / (8 * M.GP), 4), "sigma_SN^2/Delta-theta^2 = b T_sym/(8 gp), self-noise only")
        # physical calibration (Section V): one time unit = TIME_UNIT_S seconds
        gp_phys = M.GP / M.TIME_UNIT_S
        mac.add("physGp", fix(gp_phys, 2), "gamma_p in s^-1"); mac.add("physTsym", fix(M.T_SYM * M.TIME_UNIT_S, 1))
        d_um, D_um2 = 50.0, 100.0
        tpk = d_um ** 2 / (6 * D_um2)
        def h_ratio(x):                                   # h(t_peak (1 + x))/h(t_peak) for the free-diffusion pulse
            return (1 + x) ** -1.5 * math.exp(1.5 * (1 - 1 / (1 + x)))
        mac.add("physTpeak", fix(tpk, 1), "d^2/(6 D) in s at d = 50 um, D = 100 um^2/s")
        mac.add("physTsymOverTpeak", fix(M.T_SYM * M.TIME_UNIT_S / tpk, 1))
        mac.add("physIsiFirstTapTested", fix(100 * h_ratio(M.T_SYM * M.TIME_UNIT_S / tpk), 0), "% of the peak left by the previous pulse at the tested ratio")
        mac.add("physIsiFirstTapFiveS", fix(100 * h_ratio(5.0 / tpk), 0), "% at a 5 s symbol")
        mac.add("physTailSumTested", fix(sum(h_ratio(m_ * M.T_SYM * M.TIME_UNIT_S / tpk) for m_ in range(1, 80)), 2), "tail sum at the tested ratio (79 preceding pulses)")
        ratio_ = M.T_SYM * M.TIME_UNIT_S / tpk
        n_taps = 80
        mac.add("wfTaps", str(n_taps), "kernel length in symbols"); mac.add("wfPrecedingPulses", str(n_taps - 1))
        mac.add("wfLastTapWeight", sci(h_ratio((n_taps - 1) * ratio_)), "relative weight of the last retained pulse")
        jj = np.arange(1, 2_000_001, dtype=float)
        s_fin = float(np.sum((1 + ratio_ * jj) ** -1.5 * np.exp(1.5 * (1 - 1 / (1 + ratio_ * jj)))))
        s_inf = s_fin + math.exp(1.5) * 2.0 / (ratio_ ** 1.5 * np.sqrt(jj[-1]))   # integral remainder of the e^1.5 (ratio j)^(-3/2) tail
        mac.add("physTailSumInf", fix(s_inf, 2), "infinite-history tail sum at T_sym = 3 t_peak")
        trunc = sum(h_ratio(m_ * ratio_) for m_ in range(1, n_taps))
        mac.add("physTailRetainedPct", fix(100 * trunc / s_inf, 0), "% of the infinite-history interference retained by the truncated kernel")
        mac.add("physTau", fix(d["allosteric"]["tau"] * M.TIME_UNIT_S, 0))
        mac.add("physTcHeadlineMin", fix(60 * M.TIME_UNIT_S, 0)); mac.add("physTcHeadlineMax", fix(960 * M.TIME_UNIT_S, 0))
        mac.add("physGcRangeLo", fix(1e-4 / gp_phys, 3), "gamma_c/gamma_p for gamma_c = 1e-4 s^-1"); mac.add("physGcRangeHi", fix(1e-3 / gp_phys, 2))
        mac.add("dpCoregSlowKratio", fix(M.K_COREG_SLOW / M.K, 3))
        mac.add("jensenPctAllo", fix(100 * d["allosteric"]["alpha"] ** 2 * d["allosteric"]["var_dy"] / M.OMEGA_HC / 2, 1),
                "% Jensen shift of the mean affinity, alpha^2 Var(y)/2, incl. self-noise")
        mac.add("redVsFullPctAllo", fix(100 * (d["allosteric"]["var_dy_chem"] / d["allosteric"]["var_dy_reduced_chem"] - 1), 0),
                "% by which the full LNA exceeds the reduced-loop chemical noise of eq. (14)")
        mac.add("redVsFullPctCoreg", fix(100 * (d["coregulated"]["var_dy_chem"] / d["coregulated"]["var_dy_reduced_chem"] - 1), 0))

    # ---- stability boundary ----------------------------------------------------
    zc = load("zeta_crit.json")
    if zc:
        mac.add("zcRef", fix(zc["zeta_crit"], 2), "zeta_crit at alpha=1")
        mac.add("zcRhoRef", fix(zc["rho"], 3))
        mac.add("zcSfOneRatio", fix(zc["ratio_sf1"], 3), "zeta at S_f=1 over zeta_crit")
        mac.add("zcSfOneInv", fix(1 / zc["ratio_sf1"], 0))
        lin = zc["linear"]
        if "varLog200" in lin[0]:
            mac.add("zcMaxVarLog", fix(max(max(r["varLog200"], r["varLog400"]) for r in lin), 3), "largest variance of the bounded sensed occupancy over the sweep (bound 0.25)")
            mac.add("zcMinG", fix(min(min(r["gmin200"], r["gmin400"]) for r in lin), 3)); mac.add("zcMaxG", fix(max(max(r["gmax200"], r["gmax400"]) for r in lin), 3))
            mac.add("zcMaxVarLinOmega", fix(max(max(r["varOmega200"], r["varOmega400"]) for r in lin), 0), "largest Omega zeta^2 Var(dy) over the sweep")
        onset = next((r for r in lin if r["kurt400"] < -0.5), None)
        if onset:
            mac.add("zcOnsetRatio", fix(onset["zeta_over_crit"], 2))

    # ---- high-copy BEP ---------------------------------------------------------
    hc = load("bep_hc.json")
    if hc:
        devs_ = []
        for key, r in hc["configs"].items():
            label, motif = key.split("|")
            if motif == "AIF" and label in ("allosteric", "weighted", "cooperative", "coregulated", "coregulated_slow"):
                devs_.append(abs(100 * (r["var_dy_omega"] / r["var_dy_analytic"] - 1)))
            mac.add(f"hc{TAG[label]}{motif}MuZero", fix(r["mu0"], 4)); mac.add(f"hc{TAG[label]}{motif}MuOne", fix(r["mu1"], 4))
            t = TAG[label] + motif
            mac.add(f"hc{t}Bep", sci(r["bep"])); mac.add(f"hc{t}BepLo", sci(r["lo"])); mac.add(f"hc{t}BepHi", sci(r["hi"]))
            mac.add(f"hc{t}SigZero", fix(r["sigma0"], 4)); mac.add(f"hc{t}SigOne", fix(r["sigma1"], 4))
            mac.add(f"hc{t}VarDy", fix(r["var_dy_omega"], 1)); mac.add(f"hc{t}VarDyAn", fix(r["var_dy_analytic"], 1))
            mac.add(f"hc{t}VarDyAnChem", fix(r["var_dy_analytic_chem"], 2))
            mac.add(f"hc{t}MeanG", fix(r["mean_g"], 4)); mac.add(f"hc{t}Dmu", fix(r["dmu"], 3))
            mac.add(f"hc{t}BepGauss", sci(r["bep_gauss"])); mac.add(f"hc{t}MeanKd", fix(r["mean_kd"], 3))
            mac.add(f"hc{t}VarDyDev", fix(100 * (r["var_dy_omega"] / r["var_dy_analytic"] - 1), 0), "% measured vs. linear-noise approximation incl. self-noise")
        for key, r in hc["bitavg_reference"].items():
            label, motif = key.split("|")
            t = TAG[label]
            mac.add(f"hcBitavg{t}Bep", sci(r["bep"]) if r["bep"] >= 1e-8 else "<10^{-8}", "reporting floor applied"); mac.add(f"hcBitavg{t}VarDy", fix(r["var_dy_omega"], 1))
            mac.add(f"hcBitavg{t}BepRaw", sci(r["bep"]), "estimate before applying the 1e-8 reporting threshold")
            mac.add(f"hcBitavg{t}SigZero", fix(r["sigma0"], 4))
            a = hc["configs"][f"{label}|AIF"]
            mac.add(f"hcTrafficVarFactor{t}", fix(a["var_dy_omega"] / r["var_dy_omega"], 1), "Var(dy) random symbol stream / averaged input")
            mac.add(f"hcTrafficBepFactor{t}", sig(a["bep"] / r["bep"], 2), "BEP random symbol stream / averaged input")
        ref = hc["references"]
        mac.add("hcStaticNone", sci(ref["static_at_kdopt_n1"]["bep"]))
        mac.add("hcStaticNcoop", sci(ref[f"static_at_kdopt_n{M.N_COOP:g}"]["bep"]))
        a, s = hc["configs"]["allosteric|AIF"], ref["static_at_kdopt_n1"]
        mac.add("hcCostOfFeedbackAllo", sig(a["bep"] / s["bep"], 2), "adaptive / fixed-affinity optimum, static channel")
        c, ca = hc["configs"]["coregulated|AIF"], hc["configs"]["cooperative_a1|AIF"]
        mac.add("hcCoregPenalty", sig(c["bep"] / ca["bep"], 2), "co-regulated / cooperative at the same alpha")
        mac.add("hcCoregVsCoopAone", fix(c["bep"] / ca["bep"], 1))
        for lab in ("allosteric", "weighted", "cooperative", "coregulated"):
            mac.add(f"hcCaifGain{TAG[lab]}", fix(hc["configs"][f"{lab}|AIF"]["bep"] / hc["configs"][f"{lab}|CAIF"]["bep"], 1))
        mac.add("hcCoregSigRatio", fix(c["sigma1"] / c["sigma0"], 2))
        mac.add("hcGaussRatioAllo", fix(a["bep"] / a["bep_gauss"], 1), "exact binomial / Gaussian approximation")
        cp = hc["configs"]["cooperative|AIF"]
        mac.add("hcGaussRatioCoop", sig(cp["bep"] / cp["bep_gauss"], 2), "exact / Gaussian for the cooperative receiver")
        for lab in ("allosteric", "cooperative", "coregulated", "coregulated_slow", "weighted"):
            r = hc["configs"][f"{lab}|AIF"]
            if "convergence" in r:
                for n_, v in r["convergence"].items():
                    mac.add(f"hcConv{TAG[lab]}N{n_}", sci(v))
                mac.add(f"hcMaxShare{TAG[lab]}", fix(100 * r["max_traj_share"], 1), "% of the BEP from the single largest trajectory")
        if "coregulated_slow|AIF" in hc["configs"]:
            cs = hc["configs"]["coregulated_slow|AIF"]
            mac.add("hcCoregSlowOverAllo", fix(cs["bep"] / a["bep"], 2)); mac.add("hcCoregSlowOverCoop", sig(cs["bep"] / cp["bep"], 2))
            mac.add("hcCoregOverCoregSlow", sig(c["bep"] / cs["bep"], 2))
        mac.add("hcCoopOverAllo", sig(a["bep"] / hc["configs"]["cooperative|AIF"]["bep"], 2))
        mac.add("hcCoregOverAllo", sig(c["bep"] / a["bep"], 2))
        mac.add("hcWtdOverAllo", fix(hc["configs"]["weighted|AIF"]["bep"] / a["bep"], 2))

    # ---- headline --------------------------------------------------------------
    hl = load("headline.json")
    if hl:
        rows = hl["rows"]
        tau = hl["tau"]
        def get(label, S, T):
            return next(r for r in rows if r["label"] == label and abs(r["S"] - S) < 1e-9 and abs(r["T"] - T) < 1e-9)
        for label in ("allosteric", "cooperative", "coregulated", "coregulated_slow"):
            if label not in tau:
                continue
            t = TAG[label]
            mac.add(f"hl{t}Tau", fix(tau[label], 1))
            for T in hl["periods"]:
                for S in hl["swings"]:
                    r = get(label, S, T)
                    tag = f"{t}T{int(T)}S{str(S).replace('.', 'p')}"
                    mac.add(f"hl{name_ok(tag)}Adaptive", sci(r["adaptive"]))
                    mac.add(f"hl{name_ok(tag)}Static", sci(r["static_best"]))
                    mac.add(f"hl{name_ok(tag)}Gain", sig(r["gain"], 2))
                    mac.add(f"hl{name_ok(tag)}Trk", fix(100 * (math.exp(r["track_err_mean_ln"]) - 1), 0), "% tracking error of the ensemble-mean affinity")
            for T in hl["periods"]:
                rs = sorted([r for r in rows if r["label"] == label and abs(r["T"] - T) < 1e-9], key=lambda r: r["S"])
                cross = None
                for j in range(1, len(rs)):
                    if rs[j]["adaptive"] < rs[j]["static_best"] and rs[j-1]["adaptive"] >= rs[j-1]["static_best"]:
                        d0 = math.log(rs[j-1]["static_best"]) - math.log(rs[j-1]["adaptive"])
                        d1 = math.log(rs[j]["static_best"]) - math.log(rs[j]["adaptive"])
                        f = d0 / (d0 - d1)
                        cross = math.exp(math.log(rs[j-1]["S"]) + f * (math.log(rs[j]["S"]) - math.log(rs[j-1]["S"])))
                        break
                peak = max(rs, key=lambda r: r["gain"])
                tg = f"{t}T{int(T)}"
                mac.add(f"hl{name_ok(tg)}Crossover", fix(cross, 1) if cross else "--")
                mac.add(f"hl{name_ok(tg)}PeakGain", sig(peak["gain"], 2))
                mac.add(f"hl{name_ok(tg)}PeakS", fix(peak["S"], 0))
                mac.add(f"hl{name_ok(tg)}TauRatio", fix(T / tau[label], 0))
                mac.add(f"hl{name_ok(tg)}CostStatic", sig(rs[0]["adaptive"] / rs[0]["static_best"], 2), "adaptive / best non-adaptive at S = 1")
            # T_c/tau at which the S = 5 reduction factor first reaches 10 and 100 (log interpolation)
            rs5 = sorted([r for r in rows if r["label"] == label and abs(r["S"] - 5.0) < 1e-9], key=lambda r: r["T"])
            xs = [r["T"] / tau[label] for r in rs5]; gs = [r["gain"] for r in rs5]
            for thr, nm in ((10.0, "Ten"), (100.0, "Hundred"), (1000.0, "Thousand")):
                x = loginterp_x(xs, gs, thr)
                mac.add(f"hlOnset{nm}{t}", fix(x, 0) if x else "--", f"T/tau where S=5 gain reaches {thr:g}")
                if nm == "Ten" and label == "allosteric" and x:
                    mac.add("physTcMin", fix(round(x) * tau[label] * M.TIME_UNIT_S, 0), "onset(10x, S=5) x tau x time unit, seconds")
        costs = [r["adaptive"] / r["static_best"] for r in rows if r["label"] == "allosteric" and r["S"] == 1.0]
        mac.add("hlCostMin", sig(min(costs), 2)); mac.add("hlCostMax", sig(max(costs), 2))
        for lab in ("allosteric", "coregulated", "cooperative", "coregulated_slow"):
            if lab not in tau:
                continue
            r60 = get(lab, 5.0, 60.0)
            mac.add(f"hl{TAG[lab]}TSixZeroSFiveGainX", sig(r60["gain"], 2))
        for thr, nm in ((1e-3, "Three"), (1e-4, "Four")):
            rc = sorted([r for r in rows if r["label"] == "cooperative" and r["T"] == 240.0], key=lambda r: r["S"])
            ok = [r["S"] for r in rc if r["adaptive"] < thr]
            if ok:
                smax = max(ok); rs_ = next(r for r in rc if r["S"] == smax)
                mac.add(f"hlCoopTTwoFourZeroSbelow{nm}", fix(smax, 0))
                mac.add(f"hlCoopTTwoFourZeroStaticAtSmax{nm}", fix(rs_["static_best"], 2))
            else:
                mac.add(f"hlCoopTTwoFourZeroSbelow{nm}", "--"); mac.add(f"hlCoopTTwoFourZeroStaticAtSmax{nm}", "--")

    # ---- low copy --------------------------------------------------------------
    if hc and devs_:
        mac.add("hcVarDyDevMinAbs", fix(min(devs_), 0), "smallest |deviation| of the measured from the LNA variance, five receivers"); mac.add("hcVarDyDevMaxAbs", fix(max(devs_), 0))
    lc = load("bep_lc.json")
    if lc:
        R = lc["results"]
        for key, r in R.items():
            scheme, motif, om, meth = key.split("|")
            t = f"lc{TAG[scheme]}{motif}Om{om}" + ("" if meth == "exact" else "Tau")
            mac.add(f"{t}Bep", sci(r["bep"])); mac.add(f"{t}Lo", sci(r["lo"])); mac.add(f"{t}Hi", sci(r["hi"]))
            mac.add(f"{t}VarDy", fix(r["var_dy_omega"], 1)); mac.add(f"{t}VarDyAn", fix(r["var_dy_analytic"], 1))
        def pick(s_, om):
            """plotting/reporting rule: exact SSA for Omega <= 30, tau-leap (1000 traj.) for Omega >= 45"""
            k = f"{s_}|AIF|{om}|exact" if om <= 30 else f"{s_}|AIF|{om}|tauleap"
            return R[k]
        for s_ in ("allosteric", "cooperative", "coregulated", "weighted", "cooperative_a1", "coregulated_slow"):
            for om in sorted({int(k.split("|")[2]) for k in R if k.startswith(s_ + "|AIF")}):
                try:
                    r = pick(s_, om)
                except KeyError:
                    continue
                mac.add(f"lcPlot{TAG[s_]}Om{om}Bep", sci(r["bep"])); mac.add(f"lcPlot{TAG[s_]}Om{om}Lo", sci(r["lo"])); mac.add(f"lcPlot{TAG[s_]}Om{om}Hi", sci(r["hi"]))
        for s_ in ("allosteric", "cooperative", "coregulated", "weighted"):
            a, b = R[f"{s_}|AIF|20|exact"]["bep"], R[f"{s_}|CAIF|20|exact"]["bep"]
            mac.add(f"lcCaifGain{TAG[s_]}", fix(a / b, 1))
        for om in (45, 200):
            e, t = R[f"allosteric|AIF|{om}|exact"], R[f"allosteric|AIF|{om}|tauleap"]
            mac.add(f"lcXcheckAlloOm{om}", fix(t["bep"] / e["bep"], 2), "tau-leap / exact")
        mac.add("lcCoopOverAlloOmTwoZero", sig(pick("allosteric", 20)["bep"] / pick("cooperative", 20)["bep"], 2))
        mac.add("lcCoopOverAlloOmTwoZeroZero", sig(pick("allosteric", 200)["bep"] / pick("cooperative", 200)["bep"], 2))
        mac.add("lcCoregOverAlloOmTwoZero", sig(pick("coregulated", 20)["bep"] / pick("allosteric", 20)["bep"], 2))
        mac.add("lcCoregOverAlloOmTwoZeroZero", sig(pick("coregulated", 200)["bep"] / pick("allosteric", 200)["bep"], 2))
        mac.add("lcCoregOverCoopAoneOmTwoZero", sig(pick("coregulated", 20)["bep"] / pick("cooperative_a1", 20)["bep"], 2))
        mac.add("lcCoregOverCoopAoneOmTwoZeroZero", sig(pick("coregulated", 200)["bep"] / pick("cooperative_a1", 200)["bep"], 2))
        mac.add("lcWtdOverAlloOmTwoZero", fix(pick("weighted", 20)["bep"] / pick("allosteric", 20)["bep"], 2))
        try:
            mac.add("lcCoregSlowOverAlloOmTwoZero", fix(pick("coregulated_slow", 20)["bep"] / pick("allosteric", 20)["bep"], 2))
            mac.add("lcCoregSlowOverAlloOmTwoZeroZero", fix(pick("coregulated_slow", 200)["bep"] / pick("allosteric", 200)["bep"], 2))
            mac.add("lcCoregSlowOverAlloOmEightZeroZero", fix(pick("coregulated_slow", 800)["bep"] / pick("allosteric", 800)["bep"], 2))
            mac.add("lcCoregSlowOverCoopOmTwoZeroZero", sig(pick("coregulated_slow", 200)["bep"] / pick("cooperative", 200)["bep"], 2))
            mac.add("lcCoopOmOneThreeZeroBepMatched", sci(pick("cooperative", 130)["bep"]), "cooperative at about 1030 molecules")
            mac.add("lcCoopMatchedOverAllo", sig(pick("allosteric", 200)["bep"] / pick("cooperative", 130)["bep"], 2), "non-cooperative (1080 molecules) / cooperative (1027 molecules)")
            inv_c = load("design_points.json")["design"]["cooperative"]["inventory"]; inv_a = load("design_points.json")["design"]["allosteric"]["inventory"]
            mac.add("lcCoopInventoryOmOneThreeZero", fix(inv_c * 130 / M.OMEGA_HC, 0), "cooperative controller+modulator molecules at Omega = 130")
            mac.add("lcOmegaInventoryMatch", fix(inv_a / inv_c * M.OMEGA_HC, 0), "Omega at which the cooperative inventory equals the non-cooperative one")
        except KeyError:
            pass
        for s_ in ("coregulated_slow",):
            pass
        for s_ in ("allosteric", "cooperative", "coregulated", "weighted", "cooperative_a1", "coregulated_slow"):
            try:
                mac.add(f"lcFloorRatio{TAG[s_]}", fix(pick(s_, 200)["bep"] / pick(s_, 800)["bep"], 1), "BEP(200)/BEP(800): saturation")
                mac.add(f"lcFloorRatioLow{TAG[s_]}", fix(pick(s_, 20)["bep"] / pick(s_, 200)["bep"], 0), "BEP(20)/BEP(200)")
            except KeyError:
                pass
        # Omega at which the non-cooperative BEP is within a factor 2 of its Omega=800 value
        oms = sorted({int(k.split("|")[2]) for k in R if k.startswith("allosteric|AIF")})
        try:
            b8 = pick("allosteric", 800)["bep"]
            for om in oms:
                try:
                    if pick("allosteric", om)["bep"] < 2 * b8:
                        mac.add("lcSaturationOmegaAllo", str(om)); break
                except KeyError:
                    continue
        except KeyError:
            pass

    # ---- leaky integration -------------------------------------------------------
    lk = load("leaky.json")
    if lk:
        for key, r in lk["summary"].items():
            scheme, motif, gc = key.split("|")
            t = f"lk{TAG[scheme]}{motif}"
            mac.add(f"{t}Gstar", fix(r["g_star"], 3)); mac.add(f"{t}KdRatio", fix(r["kd_ratio"], 2))
            mac.add(f"{t}BepDet", sci(r["bep_det"])); mac.add(f"{t}BepGauss", sci(r["bep_gauss"]))
        r0 = next(r for r in lk["rows"] if r["scheme"] == "allosteric" and r["motif"] == "AIF" and r["gc"] == 0.0)
        for gc, nm in ((0.0005, "Em3"), (0.005, "Em2"), (0.01, "TwoEm2"), (0.025, "FiveEm2"), (0.05, "Em1")):
            r = next(r for r in lk["rows"] if r["scheme"] == "allosteric" and r["motif"] == "AIF" and abs(r["gc"] - gc) < 1e-12)
            mac.add(f"lkAllo{nm}Gstar", fix(r["g_star"], 3)); mac.add(f"lkAllo{nm}Kd", fix(r["kd_ratio"], 3))
            mac.add(f"lkAllo{nm}KdSmall", fix(r["kd_ratio_smallleak"], 3))
            pen = r["bep_det"] / r0["bep_det"]
            mac.add(f"lkAllo{nm}Bep", sci(r["bep_det"])); mac.add(f"lkAllo{nm}Penalty", fix(pen, 2) if pen < 10 else sig(pen, 2))
        # leak rate gc = 0.05 = 0.1 gamma_p, quoted in Section III-F
        r05 = next(r for r in lk["rows"] if r["scheme"] == "allosteric" and r["motif"] == "AIF" and abs(r["gc"] - 0.05) < 1e-9)
        mac.add("lkAlloGcFive", fix(r05["g_star"], 3)); mac.add("lkAlloGcFiveKd", fix(r05["kd_ratio"], 2))
        mac.add("lkAlloGcFiveBep", sci(r05["bep_det"])); mac.add("lkAlloGcFivePenalty", sig(r05["bep_det"] / r0["bep_det"], 2))
        for key, r in lk["tolerance"].items():
            scheme, motif = key.split("|")
            mac.add(f"lkTol{TAG[scheme]}{motif}TenPct", sci(r["ten_pct"])); mac.add(f"lkTol{TAG[scheme]}{motif}Twofold", sci(r["twofold"]))
            mac.add(f"lkTolNoisy{TAG[scheme]}{motif}TenPct", sci(r.get("ten_pct_noisy", float("nan"))))
            mac.add(f"lkTolNoisy{TAG[scheme]}{motif}Twofold", sci(r.get("twofold_noisy", float("nan"))))
            if motif == "AIF" and scheme in ("allosteric", "cooperative"):
                gp_phys = M.GP / M.TIME_UNIT_S
                for nm, val in (("Det", r["ten_pct"]), ("Noisy", r.get("ten_pct_noisy", float("nan")))):
                    if val == val:
                        mac.add(f"physGcMax{nm}{TAG[scheme]}", sci(val * gp_phys), "max gamma_c in s^-1 for a 10 % penalty")
                        mac.add(f"physDoubling{nm}{TAG[scheme]}", fix(math.log(2) / (val * gp_phys) / 3600, 1), "min doubling time in h")

    # ---- stochastic leak sweep --------------------------------------------------------
    ls_ = load("leaky_stochastic.json")
    if ls_:
        gcname = {0.0005: "FiveEmFour", 0.001: "EmThree", 0.0013: "OnepThreeEmThree", 0.002: "TwoEmThree", 0.003: "ThreeEmThree",
                  0.005: "FiveEmThree", 0.01: "EmTwo", 0.015: "OnepFiveEmTwo", 0.02: "TwoEmTwo", 0.03: "ThreeEmTwo"}
        gp_phys = M.GP / M.TIME_UNIT_S
        for scheme, d_ in ls_.items():
            t = TAG[scheme]
            for key, r in d_["rows"].items():
                gc = r["gc_over_gp"]
                if gc == 0:
                    mac.add(f"lkSt{t}ZeroBep", sci(r["bep"])); mac.add(f"lkSt{t}ZeroVarDy", fix(r["var_dy_omega"], 1))
                    continue
                nm = gcname.get(round(gc, 6), name_ok(f"{gc:g}"))
                mac.add(f"lkSt{t}{nm}Ratio", fix(r["ratio"], 2), f"P_e(gamma_c)/P_e(0) at gamma_c/gamma_p = {gc:g}")
                mac.add(f"lkSt{t}{nm}RatioLo", fix(r["ratio_lo"], 2)); mac.add(f"lkSt{t}{nm}RatioHi", fix(r["ratio_hi"], 2))
                mac.add(f"lkSt{t}{nm}Bep", sci(r["bep"])); mac.add(f"lkSt{t}{nm}Kd", fix(r["mean_kd"], 3)); mac.add(f"lkSt{t}{nm}G", fix(r["mean_g"], 3))
                mac.add(f"lkSt{t}{nm}VarDy", fix(r["var_dy_omega"], 1))
                if r.get("det_bep") and d_["rows"]["0"].get("det_bep"):
                    mac.add(f"lkSt{t}{nm}DetRatio", sig(r["det_bep"] / d_["rows"]["0"]["det_bep"], 2), "deterministic-shift prediction of the ratio")
            for nm, val in (("TenPct", d_.get("tol_ten_pct")), ("Twofold", d_.get("tol_twofold"))):
                mac.add(f"lkSt{t}Tol{nm}", sci(val) if val else "--", "measured tolerance, gamma_c/gamma_p")
                if val and nm == "TenPct":
                    mac.add(f"physGcMaxStoch{t}", sci(val * gp_phys), "max gamma_c in s^-1 for a measured 10 % penalty")
                    mac.add(f"physDoublingStoch{t}", fix(math.log(2) / (val * gp_phys) / 3600, 1), "min doubling time in h (measured tolerance)")

    # ---- tracking / ISI ----------------------------------------------------------
    tr = load("tracking.json")
    if tr:
        mac.add("trAlpha", fix(tr["alpha"], 3)); mac.add("trTau", fix(tr["tau"], 1))
        mac.add("trFastKd", fix(tr["A"]["fast"]["kd_final"], 2))
        mac.add("trFastThZero", fix(tr["A"]["fast"]["th0_final"], 3)); mac.add("trFastThOne", fix(tr["A"]["fast"]["th1_final"], 3))
        mac.add("trFastKdRelSdPct", fix(100 * tr["A"]["fast"]["kd_rel_sd"], 0))
        mac.add("trSlowKd", fix(tr["A"]["slow"]["kd_final"], 2))
        mac.add("trSlowThZero", fix(tr["A"]["slow"]["th0_end"], 2), "occupancy at the end of a bit-0 symbol (final eighth), alternating stream")
        mac.add("trSlowThOne", fix(tr["A"]["slow"]["th1_end"], 2), "occupancy at the end of a bit-1 symbol (final eighth), alternating stream")
        rl = [r for r in tr["B"]["reconvergence"] if r is not None]
        mac.add("trRelockMin", fix(min(rl), 0)); mac.add("trRelockMax", fix(max(rl), 0))
        mac.add("trRelockMinTau", fix(min(rl) / tr["tau"], 1)); mac.add("trRelockMaxTau", fix(max(rl) / tr["tau"], 1))
        mac.add("trTc", fix(tr["B"]["t_c"], 0))
        mac.add("trSinS", fix(tr["C"]["S"], 0)); mac.add("trSinT", fix(tr["C"]["T"], 0))
        mac.add("trSinErrPct", fix(100 * (math.exp(tr["C"]["mean_abs_log_err"]) - 1), 0))
        mac.add("trSinErrTrajPct", fix(100 * (math.exp(tr["C"]["mean_abs_log_err_traj"]) - 1), 0))
        mac.add("trSinLag", fix(tr["C"]["lag_s"], 0)); mac.add("trSinLagTau", fix(tr["C"]["lag_s"] / tr["tau"], 1))
        D = tr["D"]
        mac.add("isiTailSum", fix(D["tail_sum"], 2)); mac.add("isiCbar", fix(D["cbar"], 2)); mac.add("isiPred", fix(D["pred"], 2))
        mac.add("isiTsym", fix(D["t_sym"], 1)); mac.add("isiTpeak", fix(D["t_peak"], 2))
        for key, c in D["cases"].items():
            tag, kb = key.split("|")
            nm = ("Mem" if tag == "memoryless" else "Isi") + ("Sat" if float(kb) < 10 else "Reach")
            mac.add(f"isi{nm}Kd", fix(c["kd_mean"], 3 if tag == "memoryless" else 2)); mac.add(f"isi{nm}Ci", fix(c["ci95"], 3 if tag == "memoryless" else 2))
            mac.add(f"isi{nm}DevPct", fix(c["dev_pct"], 1)); mac.add(f"isi{nm}DevRootPct", fix(c["dev_root_pct"], 1))
            mac.add(f"isi{nm}Root", fix(c["root"], 2)); mac.add(f"isi{nm}MeanY", fix(c["mean_y"], 2))
            mac.add(f"isi{nm}FracSmallPct", fix(100 * c["frac_y_small"], 0)); mac.add(f"isi{nm}Kbase", fix(c["kbase"], 2))
            mac.add(f"isi{nm}Ntraj", c["n_traj"])
        mac.add("isiMemKd", fix(D["cases"]["memoryless|5.437"]["kd_mean"], 3)); mac.add("isiMemCi", fix(D["cases"]["memoryless|5.437"]["ci95"], 3))
        mac.add("isiNseq", D["cases"]["memoryless|5.437"]["n_traj"])

    # ---- waveform ---------------------------------------------------------------------
    wf = load("waveform.json")
    if wf:
        mac.add("wfKbase", fix(wf["kbase"], 0)); mac.add("wfTpeak", fix(wf["t_peak"], 2)); mac.add("wfCbar", fix(wf["cbar"], 2))
        mac.add("wfKmeanbias", fix(wf["K_meanbias"], 2)); mac.add("wfKheldRoot", fix(wf["K_held_root"], 2))
        mac.add("wfKcontRoot", fix(wf["K_cont_root"], 2)); mac.add("wfKbest", fix(wf["K_best_fixed"], 2))
        mac.add("wfBepBest", sci(wf["bep_best_fixed"], 2)); mac.add("wfBepAtKcont", sci(wf["bep_at_K_cont"], 2))
        mac.add("wfSstar", fix(wf["s_star"], 3)); mac.add("wfNtraj", wf["n_traj"])
        mac.add("wfContBelowPct", fix(100 * (1 - wf["K_cont_root"] / wf["K_held_root"]), 0), "% by which the continuous-sensing root lies below the peak-sample optimum")
        for key, c in wf["cases"].items():
            nm = {"held": "Held", "waveform": "Wave", "waveform_renorm": "Renorm", "waveform_renorm_g0p3": "RenormAtt"}[key]
            mac.add(f"wf{nm}Kd", fix(c["kd_mean"], 2)); mac.add(f"wf{nm}Ci", fix(c["ci95"], 2)); mac.add(f"wf{nm}Bep", sci(c["bep"], 2))
            mac.add(f"wf{nm}Target", fix(c["target"], 2))
        mac.add("wfWaveBelowPct", fix(100 * (1 - wf["cases"]["waveform"]["kd_mean"] / wf["cases"]["held"]["kd_mean"]), 0))
        mac.add("wfWaveBelowOptPct", fix(100 * (1 - wf["cases"]["waveform"]["kd_mean"] / wf["K_best_fixed"]), 0))
        mac.add("wfBepPenalty", fix(wf["cases"]["waveform"]["bep"] / wf["cases"]["held"]["bep"], 1))
        mac.add("wfSstarRoot", fix(wf.get("s_star_at_root", float("nan")), 3)); mac.add("wfBepAtKheld", sci(wf.get("bep_at_K_held", float("nan")), 2))
        mac.add("wfCostFeedback", fix(wf["cases"]["waveform_renorm"]["bep"] / wf["bep_best_fixed"], 2), "closed loop / fixed-affinity optimum, static channel, CIR-based model")
        mac.add("wfAttFactor", fix(wf["cases"]["waveform_renorm_g0p3"]["gain"], 1))
        ps = wf.get("pulsed_swing")
        if ps:
            mac.add("wfSwS", fix(ps["S"], 0)); mac.add("wfSwT", fix(ps["T"], 0)); mac.add("wfSwAdaptive", sci(ps["adaptive"], 2))
            mac.add("physPulsedTc", fix(ps["T"] * M.TIME_UNIT_S, 0), "T_c of the time-varying case under the CIR-based model, in seconds")
            mac.add("wfSwStatic", sci(ps["static_best"], 2)); mac.add("wfSwOracle", sci(ps["oracle"], 2)); mac.add("wfSwGain", fix(ps["gain"], 1))
            mac.add("wfSwStaticKd", fix(ps["static_kd"], 2))

    # ---- bounded actuator ---------------------------------------------------------------
    bd = load("bounded.json")
    if bd:
        cal = bd["calibration"]
        mac.add("bdChi", fix(bd["chi"], 0)); mac.add("bdYstar", fix(bd["y_star"], 1)); mac.add("bdBeta", fix(bd["beta_star"], 3))
        mac.add("bdKbase", fix(cal["kbase"], 2)); mac.add("bdKy", fix(cal["ky"], 1)); mac.add("bdKdMin", fix(cal["kd_min"], 3))
        mac.add("bdBound", fix((math.sqrt(bd["chi"]) - 1) / (math.sqrt(bd["chi"]) + 1), 2), "(sqrt chi - 1)/(sqrt chi + 1)")
        mac.add("bdT", fix(bd["T"], 0)); mac.add("bdSmax", fix(M.KD_OPT / cal["kd_min"], 0), "largest variation depth with the target inside the actuator range")
        for law, L in bd["laws"].items():
            t = "Exp" if law == "exp" else "Atcm"
            n = L["nominal"]
            mac.add(f"bd{t}Bep", sci(n["bep"])); mac.add(f"bd{t}VarDy", fix(n["var_dy_omega"], 1)); mac.add(f"bd{t}VarDyAn", fix(n["var_dy_analytic"], 1))
            mac.add(f"bd{t}Kd", fix(n["kd_mean"], 3)); mac.add(f"bd{t}Zeta", fix(n["zeta"], 4)); mac.add(f"bd{t}Tau", fix(n["tau"], 1))
            for r in L["swings"]:
                sname = f"S{str(r['S']).replace('.', 'p')}"
                mac.add(f"bd{t}{name_ok(sname)}Bep", sci(r["adaptive"])); mac.add(f"bd{t}{name_ok(sname)}Gain", sig(r["gain"], 2))
                mac.add(f"bd{t}{name_ok(sname)}Trk", fix(100 * (math.exp(r["track_err_mean_ln"]) - 1), 0))
        # local actuator gain of the bounded law at the fivefold-attenuated target
        M.set_actuator("atcm", kbase=cal["kbase"], ky=cal["ky"], chi=bd["chi"])
        try:
            from scipy.optimize import brentq
            y5 = brentq(lambda y: M.kd_of_y(y, 0.0) - 2.0 / 5.0, 0.0, 1e5)
            mac.add("bdBetaAtSfive", fix(float(M.beta_local(y5, 0.0)), 3)); mac.add("bdYAtSfive", fix(y5, 1))
            mac.add("bdBetaDropSfive", fix(bd["beta_star"] / float(M.beta_local(y5, 0.0)), 1), "beta*/beta at K_D = 0.4")
        finally:
            M.set_actuator("exp", kbase=M.KBASE)

    # ---- estimator convention and linear-stream attribution -------------------------
    es = load("estimator.json")
    if es:
        for lab, r in es.items():
            t = TAG[lab]
            mac.add(f"est{t}RatioStartPct", fix(100 * (r["ratio_start"] - 1), 1), "% conditional at symbol start vs marginal")
            mac.add(f"est{t}RatioEndPct", fix(100 * (r["ratio_end"] - 1), 1), "% conditional at symbol end vs marginal")
            mac.add(f"est{t}VarLinear", fix(r["var_linear_stream"], 1)); mac.add(f"est{t}VarLNA", fix(r["var_lna_bits"], 1))
            mac.add(f"est{t}LinDevPct", fix(100 * (r["var_linear_stream"] / r["var_lna_bits"] - 1), 0), "% linearized sensing, piecewise-constant symbols vs. linear-noise approximation")
            if "phase" in r:
                ph = r["phase"]
                for k_, nm_ in (("0", "Zero"), ("0.2", "Two"), ("0.4", "Four"), ("0.6", "Six"), ("0.8", "Eight"), ("1", "Ten")):
                    if k_ in ph["ratios"]:
                        mac.add(f"estPhase{t}{nm_}Pct", fix(100 * (ph["ratios"][k_] - 1), 1), f"% conditional BEP at phase {k_} vs marginal")
                mac.add(f"estPhaseMax{t}Pct", fix(ph["max_dev_pct"], 1), "largest |deviation| over the phases, %")
        if es:
            mx = max(r["phase"]["max_dev_pct"] for r in es.values() if "phase" in r)
            mac.add("estPhaseMaxAllPct", fix(mx, 1), "largest phase deviation over the four receivers")
    # ---- modification-level model ---------------------------------------------------
    mo = load("modification.json")
    if mo:
        mac.add("modSites", fix(mo["M_sites"], 0)); mac.add("modA", fix(mo["alpha"], 3), "free-energy shift per site (= alpha)")
        mac.add("modReach", fix(1 + math.log(5.0), 2), "1 + ln S at S = 5, required a m at the bottom of the variation")
        for key, c in mo["cases"].items():
            nm = {"5": "Five", "1": "One", "0.2": "Fifth", "5|M10": "Sat"}.get(key, name_ok(key))
            mac.add(f"mod{nm}Kd", fix(c["kd_mean"], 3)); mac.add(f"mod{nm}VarY", fix(c["var_y_omega"], 1)); mac.add(f"mod{nm}VarM", fix(c["var_m_omega"], 1))
            if "m_over_M_max" in c:
                mac.add(f"mod{nm}Sites", fix(c["M_sites"], 0)); mac.add(f"mod{nm}aM", fix(c["aM"], 1))
                mac.add(f"mod{nm}MoverMmean", fix(100 * c["m_over_M_mean"], 1), "% mean modified fraction at the equilibrium")
                mac.add(f"mod{nm}MoverMmax", fix(100 * c["m_over_M_max"], 1), "% max modified fraction, static channel")
                mac.add(f"mod{nm}MoverMswing", fix(100 * c["m_over_M_max_swing"], 1), "% max modified fraction over the S = 5 variation")
                mac.add(f"mod{nm}KdExact", fix(c["kd_exact_law"], 3), "exact quasi-steady law at the mean modulator concentration")
            mac.add(f"mod{nm}Bep", sci(c["bep"])); mac.add(f"mod{nm}GainSfive", sig(c["gain_S5"], 2)); mac.add(f"mod{nm}Trk", fix(100 * (math.exp(c["track_err_ln"]) - 1), 0))
    # ---- loop-speed design rule --------------------------------------------------------
    dr = load("design_rule.json")
    if dr:
        def tau_lf_of(alpha_):
            ss_ = M.steady_state("allosteric", alpha_); rho_ = ss_["z1"] / (ss_["z1"] + ss_["z2"])
            return M.GP / (M.K * rho_ * M.THETA * M.zeta_star("allosteric", alpha_))
        meas_lf = {}
        for cse, rule in zip(dr["cases"], dr["rule"]):
            tg = f"S{str(cse['S']).replace('.', 'p')}T{int(cse['T'])}"
            meas_lf[(cse["S"], cse["T"])] = tau_lf_of(cse["measured_alpha_opt"])
            mac.add(f"drRuleTau{name_ok(tg)}", fix(rule["tau_opt"], 1), "rule optimum, tau_LF units")
            mac.add(f"drSurTau{name_ok(tg)}", fix(tau_lf_of(cse["surrogate_alpha_opt"]), 1), "optimum of the Gaussian approximation, tau_LF units")
            mac.add(f"drMeasTau{name_ok(tg)}", fix(meas_lf[(cse["S"], cse["T"])], 1), "measured optimum, tau_LF units")
            mac.add(f"drMeasTauDom{name_ok(tg)}", fix(cse["measured_tau_opt"], 1), "measured optimum, dominant-pole tau (not used in the text)")
            mac.add(f"drRuleOverMeasPct{name_ok(tg)}", fix(100 * (rule["tau_opt"] / meas_lf[(cse["S"], cse["T"])] - 1), 0), "% rule vs measured optimum")
            mac.add(f"drRuleBelowMeasPct{name_ok(tg)}", fix(100 * (1 - rule["tau_opt"] / meas_lf[(cse["S"], cse["T"])]), 0), "% by which the rule underestimates the measured optimum")
            mac.add(f"drMeasAlpha{name_ok(tg)}", fix(cse["measured_alpha_opt"], 3))
            mac.add(f"drMeasBepMin{name_ok(tg)}", sci(cse["measured_bep_min"])); mac.add(f"drSurBepMin{name_ok(tg)}", sci(cse["surrogate_bep_min"]))
            row_d = next((r for r in cse["rows"] if abs(r["alpha"] - 0.384) < 1e-9), None)
            if row_d:
                mac.add(f"drDesignBep{name_ok(tg)}", sci(row_d["adaptive"])); mac.add(f"drDesignTau{name_ok(tg)}", fix(tau_lf_of(0.384), 1), "design point, tau_LF units")
                mac.add(f"drGainOverDesign{name_ok(tg)}", fix(row_d["adaptive"] / cse["measured_bep_min"], 1), "BEP at the design point / at the measured optimum")
            rows = sorted(cse["rows"], key=lambda r: -r["alpha"])
            mac.add(f"drTauMin{name_ok(tg)}", fix(tau_lf_of(rows[0]["alpha"]), 1)); mac.add(f"drTauMax{name_ok(tg)}", fix(tau_lf_of(rows[-1]["alpha"]), 1))
            mac.add(f"drBepTauMin{name_ok(tg)}", sci(rows[0]["adaptive"])); mac.add(f"drBepTauMax{name_ok(tg)}", sci(rows[-1]["adaptive"]))
        below = [100 * (1 - rule["tau_opt"] / meas_lf[(cse["S"], cse["T"])]) for cse, rule in zip(dr["cases"], dr["rule"])]
        mac.add("drRuleBelowMin", fix(min(below), 0)); mac.add("drRuleBelowMax", fix(max(below), 0))
        # smallest tracking time of the alpha-only design family (other rates fixed): tau_LF(alpha) = gamma_p/b(alpha)
        ga = np.linspace(0.2, 5.0, 4801); tl = np.array([tau_lf_of(a_) for a_ in ga]); im = int(np.argmin(tl))
        tau_lf_min = float(tl[im])
        mac.add("drTauLFmin", fix(tau_lf_min, 2), "min over alpha of gamma_p/b(alpha), non-cooperative design family, other rates fixed")
        mac.add("drAlphaTauLFmin", fix(float(ga[im]), 2), "alpha at the minimum of tau_LF (sqrt 2)")
        proj_below = []
        for cse, rule in zip(dr["cases"], dr["rule"]):
            tg = f"S{str(cse['S']).replace('.', 'p')}T{int(cse['T'])}"
            proj = max(rule["tau_opt"], tau_lf_min)
            mac.add(f"drRuleProj{name_ok(tg)}", fix(proj, 1), "candidate of (17) projected onto the feasible family")
            mac.add(f"drRuleFeasible{name_ok(tg)}", "yes" if rule["tau_opt"] >= tau_lf_min else "no")
            pb = 100 * (1 - proj / meas_lf[(cse["S"], cse["T"])]); proj_below.append(pb)
            mac.add(f"drRuleProjBelowMeasPct{name_ok(tg)}", fix(pb, 0), "% by which the projected candidate lies below the measured optimum")
        mac.add("drRuleProjBelowMin", fix(min(proj_below), 0)); mac.add("drRuleProjBelowMax", fix(max(proj_below), 0))
        r240 = next(r for r in dr["rule"] if r["S"] == 5.0 and r["T"] == 240.0); r960 = next((r for r in dr["rule"] if r["S"] == 5.0 and r["T"] == 960.0), None)
        if r960:
            mac.add("drRuleScaling", fix(r960["tau_opt"] / r240["tau_opt"], 2), "tau_opt(960)/tau_opt(240); 4^(2/3) = 2.52")
        # critical damping of the reduced non-cooperative loop: b(alpha) = gamma_p^2/4
        grid_a = np.linspace(0.05, 3.0, 2951); b_of = []
        for a_ in grid_a:
            ss_ = M.steady_state("allosteric", a_); rho_ = ss_["z1"] / (ss_["z1"] + ss_["z2"])
            b_of.append(M.K * rho_ * M.THETA * M.zeta_star("allosteric", a_))
        b_of = np.array(b_of); idx = np.where(b_of >= M.GP ** 2 / 4)[0]
        if len(idx):
            mac.add("drAlphaCrit", fix(grid_a[idx[0]], 2), "smallest alpha with b >= gamma_p^2/4 (critically damped reduced loop)")
            mac.add("drAlphaCritUpper", fix(grid_a[idx[-1]], 2), "largest alpha with b >= gamma_p^2/4")
        mac.add("drTauSat", fix(2.0 / M.GP, 0), "2/gamma_p, the saturated time constant of the underdamped reduced loop")
    # ---- co-regulated receptor gain under attenuation, reduction-factor ratios, design-rule quantities
    g_bot = 0.2
    mac.add("dpCoregNhAtBottom", fix(M.N_BASE + M.KAPPA * M.y_equilibrium("coregulated", 1.0, M.CL0_NOM * g_bot, M.CL1_NOM * g_bot), 2), "n_H(y*) of the co-regulated receiver at g = 1/5")
    mac.add("dpCoregZetaAtBottom", fix(M.zeta_star("coregulated", 1.0, M.CL0_NOM * g_bot, M.CL1_NOM * g_bot), 3), "receptor gain of the co-regulated receiver at g = 1/5")
    mac.add("dpCoregZetaDropPct", fix(100 * (1 - M.zeta_star("coregulated", 1.0, M.CL0_NOM * g_bot, M.CL1_NOM * g_bot) / M.zeta_star("coregulated", 1.0)), 0), "% drop of the co-regulated receptor gain at g = 1/5")
    hp = os.path.join(RES, "headline.json")
    if os.path.exists(hp):
        hrows = json.load(open(hp))["rows"]
        def hrow(lab, T, S):
            for r in hrows:
                if r["label"] == lab and abs(r["T"] - T) < 1e-9 and abs(r["S"] - S) < 1e-9:
                    return r
        for T, tn in ((240.0, "TTwoFourZero"), (960.0, "TNineSixZero")):
            cs, al, cp = hrow("coregulated_slow", T, 5.0), hrow("allosteric", T, 5.0), hrow("cooperative", T, 5.0)
            if cs and al and cp:
                mac.add(f"hlCoregSlowOverAlloSFive{tn}", fix(cs["adaptive"] / al["adaptive"], 2), "BEP ratio matched co-regulated / non-cooperative at S = 5")
                mac.add(f"hlCoregSlowOverCoopSFive{tn}", sig(cs["adaptive"] / cp["adaptive"], 2), "BEP ratio matched co-regulated / cooperative at S = 5")
    drp = os.path.join(RES, "design_rule.json")
    if os.path.exists(drp):
        dr_ = json.load(open(drp))
        tau_meas = {(c["S"], c["T"]): c["measured_tau_opt"] for c in dr_["cases"]}
        for c in dr_["cases"]:
            mac.add(f"drSurAlpha{name_ok('S' + str(c['S']).replace('.', 'p') + 'T' + str(int(c['T'])))}", fix(c["surrogate_alpha_opt"], 2))
        if (5.0, 960.0) in tau_meas and (5.0, 240.0) in tau_meas:
            mac.add("drMeasScaling", fix(meas_lf[(5.0, 960.0)] / meas_lf[(5.0, 240.0)], 2), "measured tau_LF,opt(960)/tau_LF,opt(240)")
    mac.write(os.path.join(NUMBERS, "numbers.tex"))
    # macros of the CIR-based model sweep, the integration-step check, and the explicit-modification check
    import run_waveform_isi, check_isi_step, check_modification_bep
    for module, name in ((run_waveform_isi, "waveform_isi.json"), (check_isi_step, "waveform_isi_step.json")):
        stored = load(name)
        if stored is not None:
            module.write_macros(stored)
    if load("bep_hc.json") is not None and load("modification.json") is not None:
        check_modification_bep.write_macros(check_modification_bep.compute())
